server:
  port: 9090
Spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/xindus
    username: root
    password: root
    driver:
      class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update